name: Merge Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup
        run: make setup

      - name: Format
        run: make format

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::error::Code formatting check failed. Please run 'make format' locally and commit the changes."
            git status
            git diff
            exit 1
          fi

      - name: Lint docs
        run: make docs-lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/*.trx'
          retention-days: 30

      - name: Build Documentation
        run: make docs-build

  report:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: List downloaded artifacts
        run: ls -R test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "test-results/**/*.trx"