name: Merge Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      run_ci: ${{ steps.check.outputs.run_ci }}
    steps:
      - name: Check if CI should run
        id: check
        run: echo "run_ci=${{ !contains(github.event.pull_request.title, 'skip ci') }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup
        run: make setup

      - name: Format
        run: make format

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::error::Code formatting check failed. Please run 'make format' locally and commit the changes."
            git status
            git diff
            exit 1
          fi

#      - name: Lint docs
#        if: ${{ needs.init.outputs.run_ci == 'true' }}
#        run: make docs-lint

      - name: Build
        run: make build

      - name: Test
        if: ${{ needs.init.outputs.run_ci == 'true' }}
        run: make test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() && needs.init.outputs.run_ci == 'true' }}
        with:
          name: test-results
          path: '**/*.trx'
          retention-days: 30

#      - name: Build Documentation
#        if: ${{ needs.init.outputs.run_ci == 'true' }}
#        run: make docs-build

  report:
    runs-on: ubuntu-latest
    needs: [ init, build ]
    if: ${{ always() && needs.init.outputs.run_ci == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: List downloaded artifacts
        run: ls -R test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "test-results/**/*.trx"