name: Merge Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      run_ci: ${{ steps.check.outputs.run_ci }}
    steps:
      - name: Check if CI should run
        id: check
        run: echo "run_ci=${{ !contains(github.event.pull_request.title, 'skip ci') }}" >> $GITHUB_OUTPUT

  run-short:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ needs.init.outputs.run_ci != 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run
        run: make ci-merge-request-short

  run-full:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ needs.init.outputs.run_ci == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run
        run: make ci-merge-request-full

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/*.trx'
          retention-days: 30

  report:
    runs-on: ubuntu-latest
    needs: [ init, run-full ]
    if: ${{ always() && needs.init.outputs.run_ci == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "test-results/**/*.trx"